-- Création de la table "users"
CREATE TABLE "User"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    firstName  VARCHAR(255),
    lastName   VARCHAR(255),
    email      VARCHAR(255),
    role       VARCHAR(255),
    manager_id BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "User"
    ADD CONSTRAINT FK_USER_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES "User" (id);

-- Création de la table "tasks"
CREATE TABLE tasks (
                       id SERIAL PRIMARY KEY,
                       title VARCHAR(100) NOT NULL,
                       description TEXT,
                       due_date DATE,
                       completed BOOLEAN DEFAULT FALSE,
                       user_id INT REFERENCES users(id) -- Foreign key pointing to the user
);
